[package]
name = "wayvr-dashboard"
version = "0.3.8"
description = "A VR dashboard for WayVR"
authors = ["oo8.dev"]
edition = "2021"
homepage = "https://oo8.dev/wayvr_dashboard"

[lib]
name = "wayvr_dashboard_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.dev]
incremental = true
strip = false
lto = false
opt-level = 0

[profile.dev.package."*"]
opt-level = 0
incremental = true

[profile.dev.build-override]
opt-level = 0
incremental = true

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }

[dependencies]
tauri = { version = "2.8.5", features = [
	"protocol-asset",
	"devtools",
	"unstable",
] }
tauri-plugin-shell = "2.3.1"
libsteamium = { path = "../libsteamium" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tauri-plugin-fs = "2.4.2"
walkdir = "2.5.0"
xdg = "3.0.0"
anyhow = "1.0.100"
rust-ini = "0.21.3"
libmonado = { git = "https://github.com/olekolek1000/libmonado-rs.git", rev = "edfbba6f47ee28181755c80531586e3eb91745c8" }
log = "0.4.28"
tauri-plugin-http = { version = "2.5.2", features = ["unsafe-headers"] }
interprocess = { version = "2.2.3", features = ["tokio"] }
bytes = "1.10.1"
tokio = "1.48.0"
tokio-util = "0.7.16"
smallvec = "1.15.1"
wayvr_ipc = { git = "https://github.com/olekolek1000/wayvr-ipc.git", rev = "a72587d23f3bb8624d9aeb1f13c0a21e65350f51", features = [
	"client",
] }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tracing = "0.1.41"
gio = "0.21.2"
glib = "0.21.3"
gtk = "0.18.2"
env = "1.0.1"
